<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <DalamudLibPath>C:\Users\t.fritzen\Projects\Private\GlamSource\reference\Dalamud\bin\Debug\</DalamudLibPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LuminaSupplemental.Excel" Version="5.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Lumina">
      <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
